### ISSUE TITLE
Support for Mathjax?

### ISSUE THREAD

**Issue by drvinceknight** [PeerJ/paper-now#10]
[Mathjax](http://www.mathjax.org/) is how mathematics gets rendered on the web (sorry for not opening up the code and taking a look myself).

**Comment by hubgit** [comment]
Absolutely! MathJax is already enabled, and [the delimiters that need to be used are documented in the wiki](https://github.com/PeerJ/paper-now/wiki/Text-Formatting).

**Comment by drvinceknight** [comment]
That's awesome!
