### ISSUE TITLE
colons in figure titles and/or descriptions break legend

### ISSUE THREAD

**Issue by katrinleinweber** [PeerJ/paper-now#17]
This appears to be a problem of Jekyll parsing the YAML block (returns: `Error reading file […].md: (<unknown>): mapping values are not allowed in this context at line […]`). Escaping with `\:` doesn't work. [Replacing with `&#58;`](http://stackoverflow.com/a/19086251) or wrapping in Markdown (`*Scale bar: 1µm*` or `**A:** … **B:** …`) both do. In the latter case however, the `*` then can't be the 1st character after YAML's `description:`, because it expects an alphanumeric one. What a rabbit hole :-D

Since colons in, as well as panel references at the start of, figure legends are desirable, I'd like to discuss ideas to solve this problem.
- applying the abstract notation with `|`, newline and two spaces to the figure title and description templates
- adding a note to the readme
- automated escaping of unsupported characters
- other way of paring figure metadata

The first two I could implement & send a pull request.

**Comment by hubgit** [comment]
Wrapping the text in double-quotes is the simplest way to avoid this, unless there are newlines, in which case `|` works better.

**Comment by rellan** [comment]
Thanks! This was driving me nuts!

**Comment by hubgit** [comment]
The example YAML [now uses double quotes where appropriate](https://github.com/PeerJ/paper-now/commit/fcb855117cc77157ddc54ff245188194c0e2a866).

**Comment by katrinleinweber** [comment]
Thanks for the hints :-)
