### ISSUE TITLE
Links from text to figures and references in sidebar

### ISSUE THREAD

**Issue by rellan** [PeerJ/paper-now#18]
Is there any way to link between a figure/reference mention in the main text to the sidebar? This would be very helpful.

**Comment by hubgit** [comment]
Yes, use the fragment identifier for the id of the figure, e.g. `#figure-1`.

Like this, for example: https://peerj.github.io/paper-now/#figure-1

**Comment by katrinleinweber** [comment]
Thanks for the hint! I found it useful to omit the domain, so that offline testing with [Jekyll Now](https://github.com/barryclark/jekyll-now) is possible with the same code (e.g. `/paper-now/#figure-1`) working online.

**Comment by hubgit** [comment]
@katrinleinweber You should only need to use the hash, as the link is relative to the current page:

``` markdown
[Figure 1](#figure-1)
```

or

``` html
<a href="#figure-1">Figure 1</a>
```

**Comment by katrinleinweber** [comment]
Even better, thanks!

**Comment by rellan** [comment]
thanks! works like a charm
