### ISSUE TITLE
Make a PDF version of article

### ISSUE THREAD

**Issue by jmrphy** [PeerJ/paper-now#22]
Ideally the article could compile into a PDF version as well. Can anyone think of a way to do that?

**Comment by hubgit** [comment]
See issue #15 :)

**Comment by jmrphy** [comment]
Oops thanks. :)

**Comment by hubgit** [comment]
I've just added [the beginnings of a print stylesheet](https://github.com/PeerJ/paper-now/commit/e5d43f179e546f1a34a6984cfa504e9981adfd39). It's not finished yet, but it includes some extra CSS that [Prince](http://www.princexml.com/) can use when creating a PDF. With that in place, a service could create a PDF using a command like this:

``` bash
prince --input=html5 --javascript $URL output.pdf
```

**Comment by RaoOfPhysics** [comment]
You're probably familiar with [PubCSS](https://github.com/thomaspark/pubcss), but if not it's worth checking out.

Also, this is perhaps too ambitious, but integration with [gh-publisher](https://github.com/ewanmellor/gh-publisher) in some way to automatically build PDFs hosted on GitHub for every new version (release), which are also linked from the sidebar, might actually be quite helpful. Admittedly, that is for LaTeX, but it may serve as inspiration.

**Comment by hubgit** [comment]
> You're probably familiar with PubCSS, but if not it's worth checking out.

Yes - Paper Now also provides a print stylesheet that works well with Prince for producing a PDF. It needs some work to finish off the rough edges, still.

> integration with gh-publisher in some way to automatically build PDFs hosted on GitHub for every new version (release),

Thanks for the link to gh-publisher. I actually think this can be done more easily (but similarly), with a simple service that provides a webhook endpoint and generates a PDF on each release, without needing to give it permission to write to the repository.

**Comment by RaoOfPhysics** [comment]
> I actually think this can be done more easily (but similarly), with a simple service that provides a webhook endpoint and generates a PDF on each release, without needing to give it permission to write to the repository.

:+1:
