### ISSUE TITLE
Incorporate citation style?

### ISSUE THREAD

**Issue by katrinleinweber** [PeerJ/paper-now#3]
Hello!

Awesome project :-) I wasn't sure if or how some kind of automatic citation styling can be included, so [I tweaked one](https://github.com/katrinleinweber/Zotero-styles/blob/master/paper-now.csl) to meet the examples in [`_sections`](https://github.com/PeerJ/paper-now/tree/gh-pages/_sections). It should at least make copy & pasting the final bibliography into [`06-references.md`](https://github.com/PeerJ/paper-now/blob/gh-pages/_sections/06-references.md).

Cheers!

**Comment by hubgit** [comment]
Hi, and thanks for the CSL contribution!

We haven't written any documentation for reference formatting yet, but the aim is that the references should be able to be formatted however the authors like, as long as they've got a clear title, authors, publication date and -- most importantly -- a link to the cited item (this link is what allows the items in the reference list to be matched up with the inline citations, so the metadata can be displayed in a popup).

I wonder if there are any other styles in the CSL repository that produce Markdown, and how they handle [rich text](http://citationstyles.org/styles/#Rich_Text) in the citation title…

**Comment by hubgit** [comment]
I've added [a "reference format" page](https://github.com/PeerJ/paper-now/wiki/Reference-Format) to the wiki, which can be updated if the style file gets into [the CitationStyles repository](https://github.com/citation-style-language/styles).

**Comment by katrinleinweber** [comment]
Merci :-)
