### ISSUE TITLE
Add links to annotation tools

### ISSUE THREAD

**Issue by hubgit** [PeerJ/paper-now#37]
Rather than loading annotation tools inline, provide links to `https://genius.it{url}` and `https://via.hypothes.is/h/{url}`.

**Comment by RaoOfPhysics** [comment]
Any way to retain formatting/layout when using via?

**Comment by hubgit** [comment]
I've found that the formatting/layout has always looked the same as the original in via.hypothes.is (except for the MathJax rendering), but not always so correct in genius.it (which is still in beta and understandably changing a lot). Do you have an example of an article that isn't rendering correctly in via.hypothes.is?

**Comment by RaoOfPhysics** [comment]
Thanks for the quick reply! I guess it's not an issue at your end. It may have to do with the Firefox extensions I have installed. I cannot replicate the issue on Chrome.

See Firefox screenshots here:

![screen shot 2015-05-07 at 13 06 02](https://cloud.githubusercontent.com/assets/7623019/7514041/22baa10a-f4ba-11e4-9c5d-0ed8991b9aec.png)

![screen shot 2015-05-07 at 13 06 06](https://cloud.githubusercontent.com/assets/7623019/7514042/22bcc3ea-f4ba-11e4-815b-4dc0a06045f9.png)

**Comment by hubgit** [comment]
I see - that must be specific to browsers like Firefox that don't yet have native support for web components.

At least the article is still readable and the annotations should still show up in both places correctly?

**Comment by hubgit** [comment]
That single-column layout should be perfectly readable after a few small improvements to the CSS (it needs to be readable by people with JS disabled, who get the same view), so hopefully it's ok to annotate in that layout as well.

**Comment by RaoOfPhysics** [comment]
I'll try it later with all extensions disabled and let you know if I still have the issue. As you say, the article is still readable. Haven't checked annotations.

**Comment by hubgit** [comment]
I tried with plain Firefox and saw the same as in the screenshots above, so it's not related to extensions.

**Comment by RaoOfPhysics** [comment]
Ah, shame. Works fine with just the hypothes.is JS called through the bookmarklet. Thanks for following up on this!

**Comment by hubgit** [comment]
> Works fine with just the hypothes.is JS called through the bookmarklet.

Great - and annotations made on the actual article using the bookmarklet/browser extension should show up in all the same places as well :sunglasses:

**Comment by RaoOfPhysics** [comment]
@hubgit: Oh, of course, I'm aware of that! :) It's just the aesthetics… :P
