### ISSUE TITLE
Add sections?

### ISSUE THREAD

**Issue by danilofreire** [PeerJ/paper-now#4]
Hello Alf!

I think `paper-now` is a great idea, congratulations! I tried to add more sections to those previously included in the folder, but unfortunately the page doesn't build correctly. I also changed `sections.html` to include the new files but it didn't work. Any suggestions?

Here's my repo if you want to check out the mess I did: https://github.com/danilofreire/invalid-votes

Thanks! :)

**Comment by hubgit** [comment]
Hi Danilo :)

Thanks for being one of the first to experiment with using Paper Now to write a paper, and you're right - it was too difficult to add new sections.

I've improved the handling of the abstract, keywords and article sections, and [sent a pull request](https://github.com/danilofreire/invalid-votes/pull/1) to bring your repository up to date.

**Comment by danilofreire** [comment]
Hi again :) 

Thanks a lot for fixing those issues. You deserve to be a co-author, too! :)

I'm looking at the files you've changed and everything seems to be alright. However, I think the page still doesn't build. I'll take a close look at the files again and I get back to you soon.

**Comment by hubgit** [comment]
It looks like it's built ok at http://danilofreire.com/invalid-votes/ - are you building locally, or on GitHub?

**Comment by danilofreire** [comment]
I tried to build it on GitHub and it didn't work (I swear! haha). But now the page seems fine, thanks a lot. Problem solved :)

**Comment by ThomasA** [comment]
BTW I can highly recommend installing GitHub's Jekyll set-up locally to test-build your paper locally (https://help.github.com/articles/using-jekyll-with-pages/#installing-jekyll). That can save you a lot of broken commits, and I speak from experience :-)

**Comment by danilofreire** [comment]
You're right, Thomas. I'll do it next time! Thanks for the tip! :)
