### ISSUE TITLE
Automated DOI-only citations

### ISSUE THREAD

**Issue by dhimmel** [PeerJ/paper-now#44]
Awesome project! One killer feature would automatically generated citations and bibliographies based on DOIs or pubmed IDs. For example [ThinkLab](http://thinklab.com/help/writing_in_markdown) uses the following markdown syntax for a DOI citation:

```
Sentence in an article section referencing my ThinkLab project [@10.15363/thinklab.4].
```

Not sure of this feature's feasibility given your current design, but I think this method is the method of the future (see this [R package as another example](https://github.com/cboettig/knitcitations)).

**Comment by hubgit** [comment]
Yes, that would be great - ideally the default would be to cite by URL (as a hyperlink), and to discover the DOI from the linked web page (or from the URL if it's a known format, e.g. if the URL is a dx.doi.org link).

I've got a couple of related tools which basically do this already (e.g. [HubMed's Citation Finder](http://git.macropus.org/citation-finder/)), so it would just be a matter of turning that into a "bibliography builder" that could parse the article HTML for reference links and build the reference list.

**Comment by hubgit** [comment]
@dhimmel Do you think it would be good enough for the inline citation to just display an icon/symbol (or a number, I suppose) and to fetch and display the citation details (using the DOI) on hover?

This would avoid having to fetch the citation details in advance and write an 'Author, Year'-style inline citation into the source.

**Comment by dhimmel** [comment]
> ideally the default would be to cite by URL (as a hyperlink)

Agreed, cite by url is the most versatile and user-friendly method. You could explicitly only support DOI or PubMed urls at the beginning, until you are able to robustly associate article metadata with a given url. I wasn't having success with url lookup in [HubMed Citation Finder](//git.macropus.org/citation-finder/), but perhaps I was misusing the tool. Altmetrics has done a decent job combining all article URLs into a single record per article.

> Do you think it would be good enough for the inline citation to just display an icon/symbol

Yes, I like numbered citations because the reader can see when the same resource is cited multiple times.

> This would avoid having to fetch the citation details in advance and write an 'Author, Year'-style inline citation into the source.

I think the  'Author, Year' citation format is inferior to numbered citations, especially on the web:
- Readers don't usually care about the first author's last name
- The readability and space-efficiency impacts are disastrous, especially when many citations are provided together.
- Many scientists don't have distinct last names
- With popups more information is just a mouse hover away

If you have properly implemented hover-based citations (so the user can copy and click links in the popup), then omitting the bibliography is an improvement rather than a shortcoming.

**Comment by hubgit** [comment]
It's not perfect yet (no numbering, and placement is a bit off with the dynamic-height popovers), but I've had a go at implementing this - try hovering over the links at the end of the Introduction in [the example article](https://peerj.github.io/paper-now/).

It looks first in the bibliography for a reference with the same URL, and if it doesn't find a match then it looks for a DOI or PMID in the URL and fetches the metadata from CrossRef or PubMed, respectively.

As each link is already in the article I haven't made it possible to interact with the popup, but that could be added if it's necessary.

**Comment by hubgit** [comment]
This is implemented now (to some extent) - an inline link that has either 👍 or 👎 as its text (indicating "agrees with" or "disagrees with" respectively) will be turned into an automatically numbered citation. 

Suggestions for other emojis to represent properties in the [Citation Typing Ontology](http://purl.org/spar/cito) are welcome 😎

Any inline link that is a DOI or PMID URL gets a popover showing the metadata for the linked article.

**Comment by dhimmel** [comment]
Great addition!

Perhaps users should be able to specify CiTO concepts without emojis. This would allow for the full range of concepts and enable ascii/keyboard-keys-only markdown files. For example, in this context, I would cite my PeerJ paper as `[cito:citesForInformation](//dx.doi.org/10.7717/peerj.705)`.

**Comment by hubgit** [comment]
This calls for a table:

| character | name | description |
| --- | --- | --- |
| 💁 | citesForInformation | The citing entity cites the cited entity as a source of information on the subject under discussion |

(admittedly facetious, but it ideally needs to be a single character so that it's still readable as a "citation here" marker when JavaScript is disabled)

**Comment by dhimmel** [comment]
In the uncommon case that JavaScript is disabled, wouldn't it be okay for a user to see:

> For example, in this context, I would cite my PeerJ paper as [cito:citesForInformation](//dx.doi.org/10.7717/peerj.705).

Currently, when I disable block javascript in firefox, I get the following display of the [example article](https://peerj.github.io/paper-now/): 

> ![screenshot from 2015-05-15 15 08 45](https://cloud.githubusercontent.com/assets/1117703/7662676/575b1af6-fb14-11e4-99ac-a76bfa7fc4c6.png)

Not sure why the emoji doesn't show up, but even if it did, I am not sure the emoji clearly indicates "citation here".
