### ISSUE TITLE
Theorem environments

### ISSUE THREAD

**Issue by j2kun** [PeerJ/paper-now#47]
Pretty much every mathematics paper has special support for a Theorem/proof environment that tracks labels. In LaTeX, one typically uses the following to set up the theorem environments

```
\usepackage{amsthm}
\newtheorem{theorem}{Theorem}
\newtheorem{corollary}[theorem]{Corollary}
\newtheorem{propn}[theorem]{Proposition}
\newtheorem{conjecture}[theorem]{Hypothesis}
\newtheorem{lemma}[theorem]{Lemma}
```

The option describes the numbering system (not that important), and after defining these one can produce a theorem/proof like

```
\begin{theorem} \label{theoremlabel}
Theorem statement
\end{theorem}

\begin{proof}
... 
\end{proof}
```

And the result is almost always like this

**Theorem:** Theorem statement.
_Proof._ ...
[right-aligned tombstone]

I would be interested to see a way to include theorems/proofs (etc) in the same way that figures are included, as separate files that can be referenced with hash labels. And then one could do something like folding/expanding proof text on demand to make a paper easer to leaf through.

**Comment by hubgit** [comment]
Would you be able to point to a real-life example of a paper with theorems/proofs, either as a PDF or - ideally - as HTML?

[An example PeerJ article with proofs](https://peerj.com/articles/467/)

**Comment by j2kun** [comment]
The Lemma 1 of the linked paper is a good example.

For examples "in the wild" you can refer to any paper on arXiv's Computational Complexity list: http://arxiv.org/list/cs.CC/recent

The most recent one is http://arxiv.org/abs/1505.03424 and Lemma 2.2 is a prototypical example. Also in particular the ability to define environments with arbitrary names is important, because we use all kinds of words like "Fact" and "Observation" and "Proposition" and "Corollary" and "Claim" when we want to emphasize the position of the statement we're proving in the logical structure of the overall paper.
