### ISSUE TITLE
Recommended structure for multiple articles per repo?

### ISSUE THREAD

**Issue by boydgreenfield** [PeerJ/paper-now#57]
Hi – First off, thanks for the work here; really like the template and the philosophy!

I do have one question, however – what do you recommend as a best practice for organizing multiple articles within a single repo? Git submodules? Something else? 

I started to modify the structure locally to support multiple articles, but as far as I can tell, Jekyll doesn't support nested collections (e.g., for `_figures.yml` and `_sections.yml`)... and I also want to avoid moving too far from this article structure here and creating an accidental fork.

Would love any recommendations or thoughts. And thanks again!

**Comment by hubgit** [comment]
If you can, the best thing to do would be to have one article per repository, then another, separate repository to link them together (potentially as git submodules, if that'll work, but maybe just as an index page linking to each article).

**Comment by hubgit** [comment]
@boydgreenfield Does that approach work for you, or does the source of all articles need to be in the same repository? I'd be interested to hear why, if so.

**Comment by boydgreenfield** [comment]
Hi @hubgit – it probably does work yes. 

We just have a bunch of related content we want to put up, so the disadvantages of having to separate everything out are: (1) it's a bit messier; (2) we may have some content that's referenced/shared across these individual articles, so we'll have to have multiple copies and keep them in sync; and (3) I anticipate the deployment workflow will be a bit messier as well (esp. for, e.g., hosting on S3/Cloudfront vs. Github Pages).

All that said, there's the strong advantage that it works out of the box this way :smile:, so those aren't complaints – just noting why I futzed around trying to get it working with multiple articles in a single repo.

**Comment by hubgit** [comment]
@boydgreenfield It'll be interesting to see how that works out for you - modular dependencies between articles is an interesting scenario, and maybe it makes sense to deposit that content somewhere permanent (figshare/Zenodo/etc) or host it as another independent repository…
