### ISSUE TITLE
Please add MarkDown support for titles

### ISSUE THREAD

**Issue by katrinleinweber** [PeerJ/paper-now#7]
`*Species name*` in the article or figure titles are not italicised. They are in the descriptions, and in the titles when using `<i>Species name</i>`. Please compare the [title and topmost figure in my test article](https://katrinleinweber.github.io/paper-now/) with the code [here](https://github.com/katrinleinweber/paper-now/commit/0075786ed2afa62ccf55edf4d295f22bc34c2337) and [here](https://github.com/katrinleinweber/paper-now/blob/gh-pages/_figures/figure-5.md).

**Comment by hubgit** [comment]
Good idea - I've [added the `markdownify` filter](https://github.com/PeerJ/paper-now/compare/c15655ef327a29de9793e4c83220945fb7b7e3b2...ec3b9ba14f535b36784793839dc3b996bee32eb3) in the places where it was missing.

**Comment by katrinleinweber** [comment]
Merci :-)

**Comment by katrinleinweber** [comment]
PS: I notices that plain URLs are not converted to clickable links, despite markdownify being set to act on the sections I tested it in. Can it generally not convert plain URLs? If yes, is using another parser/converted feasible?

**Comment by hubgit** [comment]
> I notices that plain URLs are not converted to clickable links, despite markdownify being set to act on the sections I tested it in. Can it generally not convert plain URLs?

According to the [Markdown syntax](http://daringfireball.net/projects/markdown/syntax#autolink), URLs will be automatically converted to hyperlinks if they're surrounded by angle brackets, like this:

http://example.com

**Comment by hubgit** [comment]
The problem now is that `markdownify` wraps everything in `<p>` tags, which breaks the HTML when the text being converted is not actually a paragraph. I've reverted these commits until we can find a solution.

**Comment by hubgit** [comment]
Fixed by converting inline Markdown with JavaScript: https://github.com/PeerJ/paper-now/commit/5286b1462ee36086a1fce4ad84a6f7956a81b067
